### ISSUE TITLE
Problem on OS X with Bazel 0.15.2

### ISSUE THREAD

**Issue by mtsgrd** [ProdriveTechnologies/bazel-latex#1]
First of all, thank you for providing this extension!

I ran into a problem trying this out on OS X, with Bazel 0.15.2.

```bash
$> bazel run :my_report_view
Starting local Bazel server and connecting to it...
.............
INFO: Analysed target //:my_report_view (47 packages loaded).
INFO: Found 1 target...
ERROR: /Users/mtsgrd/c/resume/BUILD:3:1: SkylarkAction my_report.pdf failed (Exit 1)
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt pdflatex.fmt
/private/var/tmp/_bazel_mtsgrd/0d605fe67c66d81e0a753bdfcbb497fc/sandbox/darwin-sandbox/2/execroot/__main__/bin/kpsewhich: /private/var/tmp/_bazel_mtsgrd/0d605fe67c66d81e0a753bdfcbb497fc/sandbox/darwin-sandbox/2/execroot/__main__/bin/kpsewhich: cannot execute binary file
/private/var/tmp/_bazel_mtsgrd/0d605fe67c66d81e0a753bdfcbb497fc/sandbox/darwin-sandbox/2/execroot/__main__/bin/mktexfmt: kpsewhich -var-value=TEXMFROOT failed, aborting early.
BEGIN failed--compilation aborted at /private/var/tmp/_bazel_mtsgrd/0d605fe67c66d81e0a753bdfcbb497fc/sandbox/darwin-sandbox/2/execroot/__main__/bin/mktexfmt line 25.
I can't find the format file `pdflatex.fmt'!
Target //:my_report_view failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.296s, Critical Path: 0.62s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Any idea what's going on?

**Comment by EdSchouten** [comment]
Hey! Thanks for using this extension! \o/

This currently breaks, because it always downloads the Linux x86-64 version of TeXLive:

https://github.com/ProdriveTechnologies/bazel-latex/blob/master/repositories.bzl#L5427

This code should be adjusted to download the appropriate tarball from this page, based on the host operating system (^F Darwin):

https://github.com/ProdriveTechnologies/texlive-modular/releases

**Comment by mtsgrd** [comment]
I love Bazel, and I got excited to see this extension since I have just rewritten my own resume in LaTeX(!)

Thanks for pointing me in the right direction, if I'm left with some spare time this weekend I might give fixing that a shot. :)

**Comment by EdSchouten** [comment]
Hi @mtsgrd,

As I wanted to get some more experience with how toolchains work in Bazel (need that for work), I went ahead and implemented Darwin support for you. Enjoy!

**Comment by mtsgrd** [comment]
Awesome, it works now! 👍
