### ISSUE TITLE
Bzlmod support

### ISSUE THREAD

**Issue by Vertexwahn** [ProdriveTechnologies/bazel-latex#116]
Bzlmod support would be nice!

**Comment by leonpohl** [comment]
Are there any updates regarding this?

**Comment by solsjo** [comment]
It would be nice! And I don't think it should be that much work. That said, I rarely have time these days. So contributions would be greatly appreciated 🙂

**Comment by ljessendk** [comment]
https://github.com/ProdriveTechnologies/bazel-latex/pull/118
