### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by fsareshwala** [ProdriveTechnologies/bazel-latex#15]
We should ensure that the build is always green. Continuous Integration with Travis CI is a good way to do this. We should integrate with Travis CI.

**Comment by regisd** [comment]
I'm not affiliated with any  of these CI platforms,  but I found that [Cirrus CI has a much better bazel support](https://cirrus-ci.org/examples/#bazel) (using the official docker image, and offering remote cache) than Travis (which just doesn't support bazel at all, so you have to download it and cache the local build artefacts yourself)

**Comment by patbro** [comment]
Last week I implemented Cirrus CI in PR #30. Might need some improvements in the near future.

**Comment by fsareshwala** [comment]
Awesome! Yeah, my intention was focused on using CI. I don't care so much about the specific vendor. I'm just most familiar with Travis CI so that's what came to mind. Thank you!
