### ISSUE TITLE
latexrun file is not executable when building

### ISSUE THREAD

**Issue by fsareshwala** [ProdriveTechnologies/bazel-latex#23]
The bazel latex build was failing because the `latexrun_file` was not executable, resulting in a traceback like this:

```
Traceback (most recent call last):
  File "external/bazel_latex/run_lualatex.py", line 62, in <module>
    env=env,
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
Target //intro_cpp:syllabus failed to build
```

The `latexrun_file` is not executable and expects that `python3` be put in front it, though it has a `#!/usr/bin/env python3` shebang at the top of the file. I've fixed this locally by appending a `python3` command in front of the `latexrun_file` argument in the `subprocess.call(...)`. Opening this issue to hopefully get this fixed in the code itself.

**Comment by fsareshwala** [comment]
Potentially fixed in https://github.com/ProdriveTechnologies/bazel-latex/pull/26 but not sure if that's the way you would prefer to go.

**Comment by patbro** [comment]
Resolved by https://github.com/ProdriveTechnologies/bazel-latex/commit/b26aea927e6de010157d5564ab852ea47ea5a21b
