### ISSUE TITLE
sha256 value availability when releasing 

### ISSUE THREAD

**Issue by MIngPAPA** [ProdriveTechnologies/bazel-latex#36]
Dear developer,
What is the sha256sum value for each release? 
Could it be available either in the release description or the release file which is needed in the WORKSPACE file? 

Best regards

**Comment by w4-jonghoon** [comment]
You can get sha256 value by the following command:
```bash
$ shasum -a 256 <tarball> | awk '{ print $1 }'
```
So, I am using `0.19` version which is described in WORKSPACE:
```bazel
http_archive(
    name = "bazel_latex",
    sha256 = "2d8d5f590cfc8aa8e6d155c37c2d3540f3ab4d23ac96a576cdda8a1cf1b1e3ed",
    strip_prefix = "bazel-latex-0.19",
    url = "https://github.com/ProdriveTechnologies/bazel-latex/archive/v0.19.tar.gz",
)
```
