### ISSUE TITLE
Support for tikz-3dplot

### ISSUE THREAD

**Issue by Vertexwahn** [ProdriveTechnologies/bazel-latex#64]
Add support for `tikz-3dplot`

I tried the following:

_packages/BUILD.bazel_ extended with:
```
latex_package(
    name = "tikz-3dplot",
    srcs = [":pgf"],
    tests = ["tikz-3dplot_test.tex"],
)
```

_tikz-3dplot_test.tex_:
```
\documentclass{report}
\usepackage{tikz-3dplot}
\begin{document}
\tdplotsetmaincoords{60}{110}
\begin{tikzpicture}[scale=5,tdplot_main_coords]
%draw the main coordinate system axes
\draw[thick,->] (0,0,0) -- (-1,0,0) node[anchor=south]{$z+$};
\draw[thick,->] (0,0,0) -- (0,1,0) node[anchor=north west]{$x+$};
\draw[thick,->] (0,0,0) -- (0,0,1) node[anchor=south]{$y+$};
\end{tikzpicture}
\end{tikzpicture}
\end{document}
```
No idea what else is needed to get it working

**Comment by patbro** [comment]
Did you perhaps already tried to add this package locally instead? https://github.com/ProdriveTechnologies/bazel-latex#local-packages

Let me know whether this works or perhaps somehow might not work for you. Feel free to re-open this issue whenever deemed necessary.
