### ISSUE TITLE
Updating TexLive

### ISSUE THREAD

**Issue by jheaff1** [ProdriveTechnologies/bazel-latex#65]
Hi,

I’m considering using this repository for a project but I’m concerned that I’ll be forced to use TexLive 2019 forevermore, or until the bazel-latex developers decide to update.

May I ask if there is a process for users of bazel-latex to use a different (newer) version of TexLive?

Thanks

**Comment by patbro** [comment]
Hi there! Currently, there is no item on the roadmap to update the TeX Live version. I'm aware that would be beneficial for many packages. Though, as already mentioned in https://github.com/ProdriveTechnologies/bazel-latex/issues/43#issuecomment-716045895 updating the Oberdiek bundle is quite some work and will cause a lot of tests to break. Hope this helps.

**Comment by Kernald** [comment]
Hi!

There is actually a quite strong reason to update: TeXLive 2022 (at least) contains universal binaries for macOS. TeXLive 2019 only has binaries for x86_64 for macOS. I understand it's a fairly big task, but if you're open to it, I'm happy to work on that.

From what I understand, this would require two steps:
 - Creating a new release in https://github.com/ProdriveTechnologies/texlive-modular, after downloading the whole 2022 TeXLive archive
 - Updating this repo, both the package list in https://github.com/ProdriveTechnologies/bazel-latex/blob/64ab20d316490c4b2e24eb594fc5c1732a4a26b8/repositories.bzl and probably broken packages

Down the line, another pull request can add support for darwin-aarch64.

Tagging a release here before doing anything would ensure that people currently using bazel-latex don't get any unexpected breakage either, and can chose to upgrade whenever they like.

**Comment by patbro** [comment]
Hi there!

Some context to the reason this repo is getting (more) stale: we're not using bazel-latex anymore within any active projects at Prodrive. Besides that, I'm not involved in software engineering at Prodrive anymore, thus also not voting for bazel-latex to be used more than we're doing now. 

Therefore, I'm happy to add you as a contributor to this repo, seen you benefit much from bazel-latex in your work. :) Let me know what works for you!

**Comment by Kernald** [comment]
Hi Patrick! Congratulations on your new gig I guess? :-) I'd be happy with that, although I'm not too familiar with the details of the lualatex invocation etc, I think I'm confident enough to help with both integrating new packages/maintaining existing ones and leading the TeXLive update process. If you think that can help, I'm in!

**Comment by patbro** [comment]
Thanks a lot! 👍 

Awesome! That will help a lot already. I've just added you as a collaborator. Please feel free to reach out via email if you have any remaining questions or just want to exchange thoughts. We will keep in touch.

**Comment by Kernald** [comment]
Thanks! I believe I'd need access to https://github.com/ProdriveTechnologies/texlive-modular as well in order to update TeXLive there?

**Comment by patbro** [comment]
That's true! Consider it done!

**Comment by Kernald** [comment]
Thanks! I'll start on that as soon as I can, probably in a few days :-)

**Comment by solsjo** [comment]
Looking forward to it!
Not being well versed in latex or Tex live, will that result in kpathsea and dvisvgm being available as modules?

**Comment by Kernald** [comment]
I'm not familiar with those specific packages, so I can't promise anything, but there's basically two parts involved to get them available as modules:
- Having them available in the TeXLive archive used by these rules. We currently use TeXLive 2019, the plan is to update to TeXLive 2022 (a few months old).
- Exposing them in the rules, as done for `translations` in #74 for example. This strictly speaking isn't necessary to have in those rules, you can define your own packages in your own repo - but I'd be happy to merge a PR adding them.

I don't have a computer handy at the moment to check if the packages you're after were available in TeXLive 2019, but I suspect they would be in TeXLive 2022.

**Comment by solsjo** [comment]
Aha! I see, I might have the nomenclature off here. And also off topic for this issue.

I guess none of them are modules / latex packages related to translation from tex to e.g. dvi.

kpathsea is a lib needed by dvisvgm.
kpathsea is part of the texlive source; and is cumbersome to build outside of the source tree.
dvisvgm is a binary which creates a svg image from latex dvi output. Typically a tikz figure. Dvisvgm is nowadays IIRC shipped with / part of tex live.

**Comment by Kernald** [comment]
Following up on the TeXLive update: https://github.com/ProdriveTechnologies/texlive-modular/releases/tag/20220321 is now ready (the artifacts are still uploading, but should be done soon). The next step will be to update this repo to take advantage of it, which I hope to do by next week.

**Comment by Kernald** [comment]
And this is now done and released in v1.2.0 :-)
