### ISSUE TITLE
Missing toolchain for arm based Macs

### ISSUE THREAD

**Issue by dendi239** [ProdriveTechnologies/bazel-latex#82]

**Comment by Kernald** [comment]
I started looking into this earlier this week (https://github.com/ProdriveTechnologies/bazel-latex/issues/65#issuecomment-1216313145), there's quite a bit of work to be done to update TeXLive before this can be done. I'll be working on that fairly soon.

**Comment by dendi239** [comment]
Cool, thank you!

**Comment by Kernald** [comment]
Fixed in #89 - released in v1.2.0.
